version: '3'

services:
  map:
    image: overv/openstreetmap-tile-server
    volumes:
      - openstreetmap-data:/var/lib/postgresql/12/main
    ports:
      - "8080:80"
    command: "run"

volumes:
  openstreetmap-data:
    external: true
